openapi: 3.0.0
info:
  title: Reading List API
  version: v1
servers:
  - url: http://localhost:5000/api  # 假設你的後端會在本地的 5000 port 運行

paths:
  /reading-list/add:
    post:
      summary: 新增一本想讀的書籍到閱讀清單
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 書籍的標題
                author:
                  type: string
                  description: 書籍的作者
              required:
                - title
                - author
      responses:
        '201':
          description: 成功新增書籍
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '400':
          description: 請求格式錯誤
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: 錯誤訊息
  /reading-list:
    get:
      summary: 獲取所有想讀的書籍列表
      responses:
        '200':
          description: 成功返回書籍列表
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
  /reading-list/{id}/delete:
    post:
      summary: 刪除一本指定 ID 的想讀書籍
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: 要刪除的書籍的唯一識別碼
      responses:
        '204':
          description: 成功刪除書籍，無返回內容
        '404':
          description: 找不到指定 ID 的書籍
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: 錯誤訊息

components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: integer
          description: 書籍的唯一識別碼
        title:
          type: string
          description: 書籍的標題
        author:
          type: string
          description: 書籍的作者
